spring:
  application:
    name: demo
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: never
springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_ACCESS_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    com.example.demo: DEBUG
